const bodyTests = require('./body')
const endnoteTests = require('./endnotes')
const citationTests = require('./citations')
const styleTests = require('../styles/tests')
const diagramTests = require('./diagrams')
const benchmark = require('./benchmark')

process.stdout.write('\n')
bodyTests()
endnoteTests()
citationTests()
styleTests()
diagramTests()
process.stdout.write('  ✔ All tests passing.')
benchmark()
